### ISSUE TITLE
Enum for Channel and Message "type" property 

### ISSUE THREAD

**Issue by PsychoTea** [PsychoTea/Oxide.Ext.Discord#10]
Channel, Message, and perhaps others have an integer "type" property which dictates some basic information about the object.
At the moment it is passed as an integer, however we should instead reference this as an enum.

Docs References:
Channel - https://discordapp.com/developers/docs/resources/channel#channel-object-channel-types
Message - https://discordapp.com/developers/docs/resources/channel#message-object-message-types

**Comment by Slut** [comment]
Added #22
