### ISSUE TITLE
User DM

### ISSUE THREAD

**Issue by MadLad1Clip** [PsychoTea/Oxide.Ext.Discord#36]
Not sure if this is already part of the system but does it support user Direct Messaging?

**Comment by MadLad1Clip** [comment]
OK found the functions but seems I might be having some problems here. I have built in this function but getting an error.

User.GetUser(Client, "USERIDHERE", user => { user.CreateDM(Client, chan => { Channel.GetChannel(Client, chan.ToString(), chan1 => { chan1.CreateMessage(Client, "TEST MESSAGE"); }); }); });

 (NullReferenceException: Object reference not set to an instance of an object)
  at Oxide.Ext.Discord.DiscordObjects.User.GetUser (Oxide.Ext.Discord.DiscordClient client, System.String userID, System.Action`1[T] callback) [0x0000e] in <c70faa7e50854fe0b707ce4ec3a240ad>:0 

Anyone able to help me out with what I might be doing wrong. Sorry I am quite new to coding C#

**Comment by recon88** [comment]
May I ask if you figured out how it works? Would appreciate an example :)
