### ISSUE TITLE
Embed Message

### ISSUE THREAD

**Issue by MadLad1Clip** [PsychoTea/Oxide.Ext.Discord#38]
Could I get some help on how to change a standard message to an embedded message? I have worked out a lot with this plugin but really not quite understanding how to set an embedded message and I would really like this for notifications.

**Comment by MadLad1Clip** [comment]
Any chance of getting some support with this?

**Comment by Slut** [comment]
```cs
            Embed embed = new Embed
            {
                title = "hey",
                fields = new List<Field>
                {
                    new Field
                    {
                        name = "a field",
                        value = "some sort of value",
                        inline = true
                    }
                }
            };
            channel.CreateMessage(client, embed);
```

**Comment by MadLad1Clip** [comment]
Thank you very much.

**Comment by Slut** [comment]
No problem, feel free to close the issue if you believe this solved your issue.

**Comment by MadLad1Clip** [comment]
Yeah, i have not tested it yet so keeping it open in case I need some more support. I will try implement it later onto my system.

**Comment by MadLad1Clip** [comment]
Yeah, I am not able to work this out is there any chance you could help me out a bit more with this in a function? Sorry, I am not that good at C# still learning. Thank you.

**Comment by MadLad1Clip** [comment]
Ok so I made a little function to call it and I am getting this error.
 error CS0246: The type or namespace name `Field' could not be found. Are you missing an assembly reference?

       private void SendChannelEmbededMessage(string channel, string MSG)
        {
            IsClientConnected();
            Embed embed = new Embed
            {
                title = "hey",
                fields = new List<Field>
                {
                    new Field
                    {
                        name = "a field",
                        value = MSG,
                        inline = true
                    }
                }
            };
            Channel.CreateMessage(Client, embed);
        }

**Comment by Slut** [comment]
Please use Embed.Field instead of Field in my instance I referenced field as a static class.

**Comment by MadLad1Clip** [comment]
That was it thank you very much I now have this working.
