### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by EgorBlagov** [PsychoTea/Oxide.Ext.Discord#49]
Hi,

I own Rust Server, with Russian players, and I'm trying to link it with your fantastic extension. But I'm facting issues with encoding, russian letters are displayed as ?????? in discord.

I've checked the code, and found out that symbols are lost here:
https://github.com/PsychoTea/Oxide.Ext.Discord/blame/master/Oxide.Ext.Discord/REST/Request.cs#L149

Why do we need this line? Can we change ASCII to UTF8?

Thanks & regards,
Egor.

**Comment by Slut** [comment]
Already done in the develop branch
